default:
    just --list --unsorted

watch:
    compile-typst-site --watch

build:
    compile-typst-site

export DEFAULT_JUSTFILE := '''
#import "../../templates/blog_post.typ": conf

#show: conf.with(
    page-title: "TODO",
    date: "1000-10-10",
)
'''
blog:
	printf '%s' "$DEFAULT_JUSTFILE" > src/blog/NEW_BLOG_POST.typ
	code src/blog/NEW_BLOG_POST.typ

post-process:
    #!/usr/bin/env python
    import sys
    import re

    input_data = sys.stdin.buffer.read()

    # Find all head tags
    heads = re.findall(rb'<head>.*?</head>', input_data, flags=re.DOTALL)

    # Replace first head with second head, then remove the original second head
    # We need to remove the second one first to avoid issues
    replaced = input_data.replace(heads[1], b'', 1)  # Remove second head
    replaced = replaced.replace(heads[0], heads[1], 1)  # Replace first with second

    sys.stdout.buffer.write(replaced)